### ISSUE TITLE
Issues header box is unstyled

### ISSUE THREAD

**Issue by jucrouzet** [StylishThemes/GitHub-Dark#793] opened 2018-12-07 23:27 UTC
* **Browser**: Chrome 73
* **Operating System**: Mac OS X Mojave
* **Screenshot**: 

![image](https://user-images.githubusercontent.com/471070/49677542-9dcc4280-fa7f-11e8-97d9-057955b7fa3a.png)

* **HTML of the section where the issue occurs**:

````html
<div class="gh-header-hide-if-sticky">
    <div class="gh-header-show ">
        <div class="gh-header-actions">
            <button type="button" class="btn btn-sm js-details-target" aria-expanded="false" aria-label="Edit Issue title" data-ga-click="Issues, edit issue, view:issue_show location:issue_header style:button logged_in:true">Edit</button>

              <a href="/vvo/selenium-standalone/issues/new" class="btn btn-sm btn-primary float-right" data-hotkey="c" data-ga-click="Issues, create new issue, view:issue_show location:issue_header style:button logged_in:true">
                New issue
              </a>
        </div>

      <h1 class="gh-header-title">
        <span class="js-issue-title">
          Selenium Server to 3.141.5
        </span>
        <span class="gh-header-number">#417</span>
      </h1>
    </div>

      <div class="gh-header-edit">
        <form class="js-issue-update js-comment" id="edit_header_386856478" action="/vvo/selenium-standalone/issues/417" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="put"><input type="hidden" name="authenticity_token" value="I4tUAhO1BNBfsDFpJG97cG9Pt3wxovEkVoFQy5ARPFvpzBEzHJleWEFt1WmHd4N7XVbStjeD41CMIZwdkZ57HA==">
          <input class="form-control edit-issue-title js-quick-submit" autofocus="autofocus" autocomplete="off" aria-label="Issue title" type="text" value="Selenium Server to 3.141.5" name="issue[title]" id="issue_title">
          <button class="btn" type="submit" data-disable-with="Updating" data-ga-click="Issues, edit issue save, view:issue_show location:issue_header style:button logged_in:true">Save</button>
          <button class="btn-link js-details-target" type="button" aria-expanded="true" data-ga-click="Issues, edit issue cancel, view:issue_show location:issue_header style:button logged_in:true">Cancel</button>
</form>      </div>

    <div class="TableObject gh-header-meta">
      <div class="TableObject-item">
          <div class="State State--green">
    <svg class="octicon octicon-issue-opened" viewBox="0 0 14 16" version="1.1" width="14" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"></path></svg>
    Open
  </div>

      </div>
      <div class="TableObject-item TableObject-item--primary">
          <a class="author" data-hovercard-type="user" data-hovercard-url="/hovercards?user_id=10560073" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="/lrocheWB" aria-describedby="hovercard-aria-description">lrocheWB</a>  opened this <span class="noun">Issue</span>
          <relative-time datetime="2018-12-03T14:59:13Z" title="3 Dec 2018, 15:59 CET">4 days ago</relative-time>
          · 0 comments
      </div>
    </div>
  </div>
````

**Comment by xt0rted** [comment] 2018-12-07 23:36
This was fixed in acc76270b620027e7e4adeb98421305b00b1278b and is part of v1.20.86. Force an update of your style to make sure you're running the latest version.

Duplicate of #785, #786, #787

**Closed by xt0rted** 2018-12-07 23:36 UTC
