### ISSUE TITLE
Sticky header backgrounds

### ISSUE THREAD

**Issue by h1nk** [StylishThemes/GitHub-Dark#1068] opened 2020-02-20 20:17 UTC
Sticky header backgrounds are transparent instead of opaque, such as in PRs.

* **Browser**: Firefox
* **Operating System**: Linux
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/pull/959
* **Screenshot**:
![image](https://user-images.githubusercontent.com/12993584/74974823-daceeb80-541d-11ea-9b77-3e82c4172c9a.png)

**Comment by silverwind** [comment] 2020-02-20 20:20
Can not reproduce. Try to update/reinstall.

**Comment by h1nk** [comment] 2020-02-20 22:06
The issue was actually caused by GitHub-FixedHeader being used with this style (see related StylishThemes/GitHub-FixedHeader#16). Should I close this issue and reopen on there?

**Comment by xt0rted** [comment] 2020-02-20 22:10
I just noticed this myself when the sticky header disappeared behind the sticky notification banner. Looks like github pushed a change out earlier that broke this. I'm not using the fixed header style, but I do have a custom one that functions similarly.

Not sure how similar the issues are between the styles but my fix was to add:

```css
body:not(.min-width-lg) .notification-shelf + .application-main .gh-header-sticky.is-stuck,
body:not(.min-width-lg) .notification-shelf + .application-main .gh-header-sticky.is-stuck + .gh-header-shadow {
  margin-top: var(--offset) !important;
}
```

**Comment by xt0rted** [comment] 2020-02-24 18:14
@h1nk can you give this a try now? It looks like GitHub just pushed a fix out for the issue page sticky header so this might not be an issue anymore.

**Comment by the-j0k3r** [comment] 2020-03-05 13:20
ping @h1nk

**Comment by h1nk** [comment] 2020-03-05 18:36
@xt0rted & @the-j0k3r

That CSS rule along with the GitHub-Dark theme does not do the sticky header behavior like GitHub-FixedHeader for me. Not sure if I'm applying it wrong.

**Comment by xt0rted** [comment] 2020-03-05 19:19
The fix I posted isn't needed now with GitHub's latest update. At least for my style.

**Comment by the-j0k3r** [comment] 2020-03-18 09:21
Is it safe to close this?

**Comment by silverwind** [comment] 2020-03-18 09:39
Guess so

**Closed by silverwind** 2020-03-18 09:39 UTC
Labels: bug :bug:
