### ISSUE TITLE
Github-Dark not working in Firefox 78.0.1 for about 5 days

### ISSUE THREAD

**Issue by OvermindDL1** [StylishThemes/GitHub-Dark#1206] opened 2020-08-05 15:16 UTC
* **Browser**: Firefox 78.0.1, don't recall it having an update anywhere around when the issue started happening
* **Operating System**: KDE Linux
* **Link to page with the issue**: All of github
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/401605/89430263-ce083080-d6fb-11ea-9f44-20b42c91b7ab.png)

For about 5 days now it started with the new notifications screen not being themed dark, though the console still reports that the github dark script is being loaded with the proper settings though it does have some errors as shown below, however it's since affected all of github and nothing is seeming themed anymore.  I've tried to `Force Update Style` a dozen times a day to no avail.

The errors in the console log in firefox for the page is:
```
09:08:37.040 Fetching github Twilight theme https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/themes/github/twilight.min.css GitHub Dark Script:400:15
09:08:37.043 Fetching codemirror Twilight theme https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/themes/codemirror/twilight.min.css GitHub Dark Script:400:15
09:08:37.045 Fetching jupyter Twilight theme https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/themes/jupyter/twilight.min.css GitHub Dark Script:400:15
09:08:37.201
Failed to load github theme file: "Twilight" GitHub Dark Script:413:19
09:08:37.201 Falling back to previous github theme of GitHub Dark Script:414:19
09:08:37.268
Failed to load jupyter theme file: "Twilight" GitHub Dark Script:413:19
09:08:37.268 Falling back to previous jupyter theme of GitHub Dark Script:414:19
09:08:37.288
Failed to load codemirror theme file: "Twilight" GitHub Dark Script:413:19
```
And indeed, those URL's are 404'ing.

**Comment by the-j0k3r** [comment] 2020-08-06 12:03
@OvermindDL1

> though the console still reports that the github dark script 

If you mean https://github.com/StylishThemes/GitHub-Dark-Script then that is beyond broken and is unsupported, we have **archived** that repo a while back because usercss does the same, works better and users have a better OOBE.

For best results **uninstall GitHub Dark Script** and **follow https://github.com/StylishThemes/GitHub-Dark#installation**

I can confirm this works and you have no such issue.

Im closing this based on your report for GitHub Dark Script as solution is as above.

Thanks again.

**Closed** 2020-08-06 12:03 UTC
Labels: bug :bug:
