### ISSUE TITLE
Linewise comment thread, avatar connector line covers current user avatar

### ISSUE THREAD

**Issue by danseely** [StylishThemes/GitHub-Dark#610] opened 2018-05-03 15:12 UTC
* **Browser**: Chrome, Version 66.0.3359.139 (Official Build) (64-bit)
* **Operating System**: macOS Version 10.13.4 (17E202)
* **Screenshot**:
Style off:
<img width="81" alt="add_ability_to_bulk_add_remove_sources_from_leads_by_chriscain_ _pull_request__6173_ _nutshellcrm_nutshell" src="https://user-images.githubusercontent.com/2266893/39585369-a44db4a4-4ec2-11e8-993a-b74e4018f613.png">

Style on:
<img width="80" alt="add_ability_to_bulk_add_remove_sources_from_leads_by_chriscain_ _pull_request__6173_ _nutshellcrm_nutshell" src="https://user-images.githubusercontent.com/2266893/39585344-9231dbe2-4ec2-11e8-855d-2b8feac84b61.png">

**(Private repo, no link)**

* **HTML of the section where the issue occurs**:

````html
<div class="review-comment-contents">
        <h4 class="f5 text-normal d-inline">
          <strong>
              <a class="author link-gray-dark" data-hovercard-user-id="1836550" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="/chriscain" aria-describedby="hovercard-aria-description">chriscain</a> 
          </strong>
          <span class="text-gray">

              <a href="#discussion_r185813067" class="timestamp d-inline-block">
                <relative-time datetime="2018-05-03T14:16:51Z" title="May 3, 2018, 10:16 AM EDT">an hour ago</relative-time>
              </a>

          </span>
        </h4>

        


          <div class="js-minimize-comment d-none">
            

<div class="flash flash-warn my-2">
  <button class="flash-close js-comment-hide-minimize-form" type="button"><svg aria-label="Cancel hiding comment" class="octicon octicon-x" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.48 8l3.75 3.75-1.48 1.48L6 9.48l-3.75 3.75-1.48-1.48L4.52 8 .77 4.25l1.48-1.48L6 6.52l3.75-3.75 1.48 1.48z"></path></svg></button>
  <h3 class="f5">Choose a reason for hiding this comment</h3>
  <p class="mb-3">The reason will be displayed to describe this comment to others. <a href="#">Learn more</a>.</p>
  <!-- '"` --><!-- </textarea></xmp> --><form class="js-comment-minimize" action="/nutshellcrm/nutshell/community/minimize-comment" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="put"><input type="hidden" name="authenticity_token" value="sx+oRLoBrgFOFDv2TeC38jNlUq677bfCtEaflZQgkggKqHBh9NDjgHHplEsXTgZjtzthtbjAfZz7cFIRT52GXw==">
    <div class="d-inline select-menu js-menu-container js-select-menu">
      <input type="hidden" name="comment_id" value="MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDE4NTgxMzA2Nw==">
      <select name="classifier" class="form-select mr-2" aria-label="Reason" required="">
        <option value="">
          Choose a reason
        </option>
        <option value="SPAM">Spam</option>
<option value="ABUSE">Abuse</option>
<option value="OFF_TOPIC">Off Topic</option>
<option value="OUTDATED">Outdated</option>
<option value="RESOLVED">Resolved</option>
      </select>
    </div>
    <button class="btn">
      Hide comment
    </button>
</form></div>

          </div>



        <task-lists sortable="">
          <div class="comment-body markdown-body  js-comment-body">
            <p>Yeah, I just copied it. Since it's working and hopefully will never be touched again I'm going to leave it for now.</p>
          </div>
        </task-lists>

          

<div class="comment-reactions  js-reactions-container js-socket-channel js-updatable-content" data-channel="reaction:pull-request-review-comment:185813067" data-url="/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDE4NTgxMzA2Nw==/comments/reactions">
</div>

      </div>
````

**Comment by Mottie** [comment] 2018-05-03 21:00
Hi @danseely!

Thanks for reporting this problem. It'll get fixed in the master branch shortly, and available with the next release.

Duplicate of #609.

**Closed** 2018-05-03 21:02 UTC
