### ISSUE TITLE
White underline on new preview navbar

### ISSUE THREAD

**Issue by 0x11DFE** [StylishThemes/GitHub-Dark#1134] opened 2020-06-19 11:41 UTC
* **Browser**: All
* **Operating System**: All
* **Link to page with the issue**: On any repository
* **Screenshot**: [![Preview](https://i.imgur.com/cAKNChI.png)](https://i.imgur.com/cAKNChI.png)

Got this issue once enabled the new preview features.

[![FeaturePreview](https://i.imgur.com/Pj2vX4z.png)](https://i.imgur.com/Pj2vX4z.png)

**Comment by the-j0k3r** [comment] 2020-06-19 15:54
this in a way is a duplicate of https://github.com/StylishThemes/GitHub-Dark/issues/1123

closing

**Closed by the-j0k3r** 2020-06-19 15:54 UTC
Labels: bug :bug:
