### ISSUE TITLE
Line covering reply avatar in PR review comments

### ISSUE THREAD

**Issue by stevenvachon** [StylishThemes/GitHub-Dark#609] opened 2018-05-03 15:09 UTC
![screen shot 2018-05-03 at 11 07 56 am](https://user-images.githubusercontent.com/170197/39585282-6757b4d2-4ec2-11e8-9089-bc9c9a6dd1d6.png)

Using Safari 11.1

**Comment by Mottie** [comment] 2018-05-03 21:01
Hi @stevenvachon!

Thanks for reporting this problem. It'll get fixed in the master branch shortly, and available with the next release.

Duplicate of #610.

**Closed** 2018-05-03 21:01 UTC
