### ISSUE TITLE
Pull Request text & comments are not inheriting `color: #AFAFAF`

### ISSUE THREAD

**Issue by tfarrell-neurala** [StylishThemes/GitHub-Dark#995] opened 2019-09-06 18:29 UTC
* **Browser**: Chrome
* **Operating System**: OSX
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/pull/959
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/47113138/64451676-ac00cb00-d0b2-11e9-8152-eb2a591d05af.png)

**Comment by xt0rted** [comment] 2019-09-06 18:35
Duplicate of #993 

This was fixed in v1.22.85, try forcing an update to get the changes.

**Closed by xt0rted** 2019-09-06 18:35 UTC
Labels: bug :bug:
