### ISSUE TITLE
Explore nav menu selected item color isn't styled

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#918] opened 2019-04-18 19:50 UTC
* **Browser**: chrome & kiwi browser
* **Operating System**: win10 & android 9
* **Link to page with the issue**: https://github.com/explore
* **Desktop Screenshot**:

![image](https://user-images.githubusercontent.com/831974/56387154-92d5ab80-61f1-11e9-8aa8-f3977fe4c7e5.png)

* **Mobile Screenshot**:

![image](https://user-images.githubusercontent.com/831974/56387128-83eef900-61f1-11e9-89a5-a97c350ae330.png)

**Comment by the-j0k3r** [comment] 2019-04-19 07:10
Aside from the tab color, which Ill push fixes for in a sec, It looks OK in Firefox with GHD 1.21.41

![generic](https://user-images.githubusercontent.com/31389848/56411712-f3142e00-6281-11e9-8b20-7bd0eb7a2356.gif)

![generic](https://user-images.githubusercontent.com/31389848/56411876-83eb0980-6282-11e9-8d12-063928d971b5.gif)

Ill see if I can find a better android 9 user-agent, or send the one youre using?

**Comment by xt0rted** [comment] 2019-04-19 07:21
Looks like the recent regenerate fixed the text color. I'm still seeing a bottom border on hover/tap for the `Explore` link though.

**Comment by the-j0k3r** [comment] 2019-04-19 07:35
Its missing maybe

```
.subnav-primary.selected {
    border-bottom-color: transparent;
}
```

**Comment by the-j0k3r** [comment] 2019-04-19 07:41
This should be picked up by generator, but doesnt seem like it is

https://github.com/StylishThemes/GitHub-Dark/blob/88f6bcc8085e18d398058359b5c1e9bb2d3803fd/tools/generate.js#L43

Let me see if I can find out why. (probably positioning?)

**Comment by the-j0k3r** [comment] 2019-04-19 07:59
https://github.com/StylishThemes/GitHub-Dark/commit/dc5a0239c10df4fce1a36dec204b6fc116d85fb2 works here.

**Comment by the-j0k3r** [comment] 2019-04-19 08:43
Well this

**Comment by the-j0k3r** [comment] 2019-04-19 09:28
ugh OK 2 more cups of coffee and seems https://github.com/StylishThemes/GitHub-Dark/commit/cc55ed55944e6fcd702775ee4145be7764145ba8 is OK.

GitHub selected tab color has same fix. It works independently form GHD or together.

Sorry for noise :/

**Comment by silverwind** [comment] 2019-04-29 17:34
Hopefully fixed in https://github.com/StylishThemes/GitHub-Dark/commit/92ee1a98cbc017344d3e553e35e757211c062554. Issue is that a desktop style is interfering on mobile. Luckily GitHub has a `border-bottom-color: transparent` rule in their mobile sheet, so this was fixable by just reordering the transparent rule.

**Comment by the-j0k3r** [comment] 2019-04-30 08:04
@silverwind, no its not.

What the issue is atm is that the mobile explorer tab does not have a bottom border, while on desktop it does.

Currently GHD applies a bottom border on mobile also.

![generic](https://user-images.githubusercontent.com/31389848/56948047-38144c00-6b2f-11e9-8061-22d10c65766a.gif)

Ill reopen this and leave it. (I cant fix this without @media rules)

**Comment by the-j0k3r** [comment] 2019-05-05 06:53
closing this in favor of https://github.com/StylishThemes/GitHub-Dark/issues/918#issuecomment-487854934

**Closed** 2019-05-05 06:53 UTC
Labels: bug :bug:, re-opened issue 🚨
