### ISSUE TITLE
Pasting GitHub Access Token window of `GitHub Hovercard` extension is not fully styled

### ISSUE THREAD

**Issue by Geeyun-JY3** [StylishThemes/GitHub-Dark#1175] opened 2020-07-11 06:08 UTC
Pasting GitHub Access Token window of `GitHub Hovercard` extension is not fully styled. 
* **Browser**: Cent Browser 4.2.10.171 (64-bit) (Chromium 80.0.3987.163), Chrome 83.0.4103.116 (Official Build) (64-bit)
* **Operating System**: Windows 10
* **Link to page with the issue**: any page while `GitHub Hovercard` is working
* **Screenshot**:
![image](https://user-images.githubusercontent.com/49396421/87217774-818d3780-c37f-11ea-9be5-f722529d1ea6.png)

**Comment by the-j0k3r** [comment] 2020-07-11 12:24
@Geeyun-JY3 Can you inspect those white elemnets and gve us the selectors and colors that need replacing please?

**Comment by the-j0k3r** [comment] 2020-07-11 12:29
also from your screenshot I guess you may want to use https://github.com/StylishThemes/GitHub-Selected-Tab-Color

we have other addon styles also https://github.com/StylishThemes/GitHub-Dark#additional-userstyles

**Comment by silverwind** [comment] 2020-07-11 12:48
No idea how to procure that overlay but I'm confident it should be fixed.

**Comment by Geeyun-JY3** [comment] 2020-07-11 13:13
> No idea how to procure that overlay but I'm confident it should be fixed.

Fixed! Thx.

**Comment by Geeyun-JY3** [comment] 2020-09-05 06:25
@silverwind It seems that the fixe doesn't work consistently.
![image](https://user-images.githubusercontent.com/49396421/92299250-3d837100-ef83-11ea-85d0-ec828bb01d39.png)
![image](https://user-images.githubusercontent.com/49396421/92299286-a8cd4300-ef83-11ea-94fe-919f3dbe273d.png)

**Comment by silverwind** [comment] 2020-09-07 17:17
Please provide steps how to conjure that overlay.

**Comment by Geeyun-JY3** [comment] 2020-09-08 07:39
I am not sure the following steps can reproduce it. 
It seems that this bug relates to the Chromium version. And I can reproduce it in a browser whose Chromium version is 80.0.3987.163, but cannot reproduce it in a browser whose is 85.0.4183.83.

I reproduce it mostly in repository page (such as https://github.com/StylishThemes/GitHub-Dark, https://github.com/DIYgod/RSSHub) and issue page (such as #1175). I also doubt whether the`#` in the URL would make a difference, as is showed in the screenshots above.

**Comment by silverwind** [comment] 2020-09-08 11:26
Can you show the HTML of that box? E.g. open Devtool, inspect element, copy/paste HTML.

**Comment by Geeyun-JY3** [comment] 2020-09-08 12:09
I click the `Copy outerHTML` and get this:
```
<div class="ghh-overlay">
        <form>
          <h3><svg class="octicon" width="14" height="16" viewBox="0 0 14 16"><path d="M12.83 2.17C12.08 1.42 11.14 1.03 10 1c-1.13.03-2.08.42-2.83 1.17S6.04 3.86 6.01 5c0 .3.03.59.09.89L0 12v1l1 1h2l1-1v-1h1v-1h1v-1h2l1.09-1.11c.3.08.59.11.91.11 1.14-.03 2.08-.42 2.83-1.17S13.97 6.14 14 5c-.03-1.14-.42-2.08-1.17-2.83zM11 5.38c-.77 0-1.38-.61-1.38-1.38 0-.77.61-1.38 1.38-1.38.77 0 1.38.61 1.38 1.38 0 .77-.61 1.38-1.38 1.38z"></path></svg> GitHub Access Token</h3>
          <p>GitHub limits unauthenticated API requests to 60 per hour, but after binding your access token you will be able to enjoy the rate limit of <strong>5,000</strong> requests per hour.</p>
          <p>You should at least add permission for <code>public_repo</code> to enable star/unstar, and <code>user:follow</code> to enable follow/unfollow.</p>
          <p>
            <input class="ghh-token form-control" type="text" placeholder="Paste access token here..." size="40">
            <button class="btn btn-primary ghh-save">Save</button>
            <button class="btn ghh-cancel">Cancel</button>
          </p>
        </form>
      </div>
```

**Comment by silverwind** [comment] 2020-09-08 16:04
Looks as expected and we match that using `html[class^="ghh"] .ghh-overlay form`. Can you post the `class` attribute on your `<html>` node when you see that popup?

**Comment by Geeyun-JY3** [comment] 2020-09-08 23:48
> Can you post the `class` attribute on your `<html>` node when you see that popup?

How can I get this?

**Comment by the-j0k3r** [comment] 2020-09-09 13:23
> How can I get this?

read https://unito.io/blog/inspect-element-in-google-chrome-how-to-do-it-and-why-its-useful/ for instance

**Comment by silverwind** [comment] 2020-09-09 16:25
Just open the devtools inspector tab and scroll to to top to see the `<html>` node. A screenshot of it is fine too.

I'm pretty certain the issue is the `[class^="ghh"]` selector, just want to be sure.

**Comment by Geeyun-JY3** [comment] 2020-09-09 23:45
@the-j0k3r I mean: how can I get the `class` attribute on your `<html>` node when I see that popup? 
I know how to inspect element (and this is how I get the code of https://github.com/StylishThemes/GitHub-Dark/issues/1175#issuecomment-688824281), but I don’t know how to get what you want.

**Comment by Geeyun-JY3** [comment] 2020-09-10 00:28
It seems that this is a bug relating to [Refined GitHub](https://github.com/sindresorhus/refined-github) instead of  the Chromium version🤦‍♂️.
![image](https://user-images.githubusercontent.com/49396421/92667656-18a24b80-f33f-11ea-910a-36d3107047e9.png)

**Comment by silverwind** [comment] 2020-09-10 07:09
Yes, this confirms our selector is too naive, will fix.

**Closed** 2020-09-10 07:11 UTC
Labels: bug :bug:
