### ISSUE TITLE
GitHub doesn't loads when GitHub Dark is active

### ISSUE THREAD

**Issue by Kvaibhav01** [StylishThemes/GitHub-Dark#1122] opened 2020-06-12 14:01 UTC
Recently, whenever I open any webpage on GitHub it loads for a second (I can see the page content) and then it goes blank. Only the background black color shows up and nothing else is seen. When I see the Chrome Dev Tools I get the following errors:

> Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src github.githubassets.com". 

> analytics.min.js:6 POST https://www.google-analytics.com/collect net::ERR_BLOCKED_BY_CLIENT

* **Browser**: Google Chrome Version 83.0.4103.97 (Official Build) (64-bit)
* **Operating System**: Windows 10 Version 1903
* **Link to page with the issue**: N/A
* **Screenshot**: 
![Error image](https://user-images.githubusercontent.com/11731837/84510418-b6f02800-ace2-11ea-8e14-69a5f1c55a29.png)

When I disable it, the page is automatically shown. This is happening 2-3 days from now. Before this everything worked perfectly.

**Comment by the-j0k3r** [comment] 2020-06-12 14:15
Unable to duplicate.

**Comment by Kvaibhav01** [comment] 2020-06-12 17:15
@the-j0k3r, didn't quite get you...

**Comment by silverwind** [comment] 2020-06-12 18:33
The errors are probably unrelated. Do you see any HTML in the devtools inspector when it happens? There should also be a `<style>` tag that contains our CSS.

**Comment by xt0rted** [comment] 2020-06-12 19:31
I get these errors even with the style disabled. I'm not sure exactly what's triggering them, but once I navigate around for a bit they start to show up.

![image](https://user-images.githubusercontent.com/831974/84539565-a5e2ef00-acc1-11ea-9f56-57dc2b4454bb.png)

The last error in your screenshot shows analytics being blocked, it's possible your ad blocker is causing the site to not load correctly.

**Comment by silverwind** [comment] 2020-06-12 19:41
Yes, `ERR_BLOCKED_BY_CLIENT` is the adblocker, completely normal. The font errors are GitHub's fault presumably.

**Comment by Kvaibhav01** [comment] 2020-06-13 07:43
@silverwind yes, I do see the HTML but only of Stylus not of the GitHub when I enable it.

![HTML](https://user-images.githubusercontent.com/11731837/84563133-f5cfbd80-ad76-11ea-98f8-7eb1504e029d.png)

@xt0rted turning off adblocker also doesn't work but yes, that analytics error does go away. 

After turning off adblocker and turning on Stylus I just get the refused to load the font error. If this is a GitHub issue then why doesn't it happen on Incognito mode? The fonts do load as they should when there are no extensions in Incognito.

**Comment by the-j0k3r** [comment] 2020-06-17 16:43
@Kvaibhav01 I dont think the issue is related to the style, but to make 100% sure, You should only test this in a new browser profile with stylus + the style and nothing else.

**Comment by silverwind** [comment] 2020-06-17 16:59
Empty rendering could be graphics related as well, would try disabling hardware accelleration.

**Comment by the-j0k3r** [comment] 2020-07-22 09:35
I'll be closing this, Theres no way this is GHD darks fault

Also theres no feedback regarding my suggestion, in any case cant duplicate, none can.

**Closed** 2020-07-22 09:37 UTC
Labels: bug :bug:
