### ISSUE TITLE
Heart Emoji

### ISSUE THREAD

**Issue by julmot** [StylishThemes/GitHub-Dark#532] opened 2017-09-04 13:44 UTC
Example: https://github.com/julmot/mark.js/issues/159#issuecomment-326912344

* **Browser**: Firefox 55
* **Operating System**: Windows 10
* **Screenshot**:

![2017-09-04 15_43_35- bug doesn t highlight words between html tags issue 159 julmot_mark js](https://user-images.githubusercontent.com/8310677/30029065-e9a0acc6-9187-11e7-9187-a16758ecd3e6.png)

* **HTML of the section where the issue occurs**:

````html
<button class="btn-link reaction-summary-item tooltipped tooltipped-se tooltipped-multiline " name="input[content]" type="submit" value="HEART react" aria-label="whaberek reacted with heart emoji">
            <g-emoji alias="heart" class="emoji mr-1" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png" ios-version="6.0">❤️</g-emoji>
            1
          </button>
````

**Comment by silverwind** [comment] 2017-09-04 18:56
Hmm this must be something specific for Firefox on Windows 10. @Mottie can you reproduce this?

**Comment by silverwind** [comment] 2017-09-04 18:58
@julmot is it only the heart that fails to display for you? See https://github.com/StylishThemes/GitHub-Dark/wiki/Emoji for a table of all emojis.

**Comment by julmot** [comment] 2017-09-04 19:05
According to the emojis you've added above, yes. And I see all emojis in the URL you've posted, just not on GitHub.

**Comment by Mottie** [comment] 2017-09-04 19:08
Odd, I can see the heart emoji no problem.

**Comment by silverwind** [comment] 2017-09-04 19:14
@julmot can you right-click inspect on the space where the heart should be and show the font tab of the DevTools Inspector, like seen below?

<img width="488" alt="screen shot 2017-09-04 at 21 13 03" src="https://user-images.githubusercontent.com/115237/30036709-fc622780-91b5-11e7-9530-66960eda7e92.png">

**Comment by Mottie** [comment] 2017-09-04 19:18
Mine is set to "Segoe UI Emoji" inside of the `<g-emoji>` wrapper.

**Comment by julmot** [comment] 2017-09-04 20:30
![2017-09-04 22_29_55-heart emoji issue 532 stylishthemes_github-dark](https://user-images.githubusercontent.com/8310677/30037994-9b8c8a08-91c0-11e7-8c85-f70e7727a79c.png)

**Comment by silverwind** [comment] 2017-09-04 20:38
> And I see all emojis in the URL you've posted, just not on GitHub.

Not sure I follow, the link to our wiki should render emojis like everywhere else in GitHub. Are you sure it's only the heart one that's affected?

**Comment by Mottie** [comment] 2017-09-04 20:41
The emoji's on the wiki page are not rendered the same... the wiki page contains all images:

```html
<img class="emoji" title=":bowtie:" alt=":bowtie:" src="https://camo.githubusercontent.com/addfe75dc7154563f53ecd560450d07d4efada1f/68747470733a2f2f6173736574732d63646e2e6769746875622e636f6d2f696d616765732f69636f6e732f656d6f6a692f626f777469652e706e67" height="20" width="20" align="absmiddle" data-canonical-src="https://assets-cdn.github.com/images/icons/emoji/bowtie.png">
```

**Comment by silverwind** [comment] 2017-09-04 21:07
Ah, didn't know that the wikis still render image emojis.

@julmot I assume these emoji here are also invisible to you? `❤️`, ❤️

**Comment by julmot** [comment] 2017-09-04 21:09
@silverwind Yes.

**Comment by silverwind** [comment] 2017-09-04 21:16
I'm kind of out of ideas. Can you check in the DevTools for any odd styles affecting the `<g-emoji>`. Also make sure that "Show Browser Styles" is enabled in the DevTools settings so you can see styles added by extensions.

**Comment by julmot** [comment] 2017-09-04 21:23
Honestly, I don't have the time to dig into this with more detail, but from my point of view there's just no icon generated like for the other emojis:

![2017-09-04 23_23_02-heart emoji issue 532 stylishthemes_github-dark](https://user-images.githubusercontent.com/8310677/30038726-1af5aa02-91c8-11e7-9048-d36cf7162c18.png)

**Comment by xt0rted** [comment] 2017-09-05 00:15
I'm seeing this in FF on Win10 too, just not the same as @julmot is. There's a number of issues with the heart emoji on Win10 which look to be fixed in the Fall Creators Update. I've also reported a number of them to GitHub in the past thinking they were issues with the site when they actually weren't.

This is what I'm seeing in Chrome & FF without the dark theme (FF on top, Chrome on the bottom). 

![image](https://user-images.githubusercontent.com/831974/30040314-9e7f0016-91ab-11e7-89f8-db2ccc62ef0d.png)

Turning the theme on doesn't change the heart's visibility anywhere, and the only spot it's not visible for me is in that code block.

The other spot I don't see the heart is in dev tools. If you edit the node as html and move the cursor through the text it'll seem as if it pauses where the emoji should be, that's because the character is there, it's just not visible because of the spacing around it. This is also why if you place two heart emojis next to each other they overlap. It's also the only emoji that's not the same size as the rest.

This image is actually 4 emojis, 2 celebrate, 2 heart with no space between them, and then 2 heart with a single space between them.

![image](https://user-images.githubusercontent.com/831974/30040464-83181a18-91ad-11e7-90ee-ae85d1dc2d3f.png)

```
Heart Emoji 🎉🎉 ❤️❤️ ❤️  ❤️
```

**Comment by xt0rted** [comment] 2017-09-05 00:22
Just checked my previous comment in the latest insider build of Edge and the heart is rendering as expected with proper spacing. I don't have FF on that machine but I'm fairly confident that on [October 17th](https://blogs.windows.com/windowsexperience/2017/09/01/create-and-play-this-holiday-with-the-windows-10-fall-creators-update-coming-oct-17/) this won't be an issue anymore.

**Comment by the-j0k3r** [comment] 2017-09-15 08:56
Have you tried using github font revert for stylish?

**Comment by Mottie** [comment] 2017-09-15 13:00
> should work in the Stylish addon 2.0.7

Eww, try out the [Stylus](https://github.com/openstyles/stylus) extension!

**Comment by the-j0k3r** [comment] 2017-09-16 07:19
Im actually using both to be honest. 😁 

Stylus has all my its and pieces, and stylish only has my toolbars script silverwind makes because you cant style toolbars in stylus and it looks like you never will be able to.

**Comment by OvermindDL1** [comment] 2017-09-19 18:38
> Stylus has all my its and pieces, and stylish only has my toolbars script silverwind makes because you cant style toolbars in stylus and it looks like you never will be able to.

Hmm?  You should be able to style anything in a page?

**Comment by silverwind** [comment] 2017-09-19 18:45
> Hmm? You should be able to style anything in a page?

Firefox scrollbars cannot be styled throught ordinary means. Until 57, it was possible but that's no longer going to work - https://github.com/silverwind/overlay-scrollbars/issues/1.

**Comment by OvermindDL1** [comment] 2017-09-19 19:16
Ah firefox, I use it in chrome so I'd not seen that issue.

So toolbars instead of scrollbars then, right.  ^.^;

**Comment by the-j0k3r** [comment] 2017-09-19 20:46
Meant scrollbars. not toolbars 🐘

**Comment by Mottie** [comment] 2017-10-17 04:23
> Firefox scrollbars cannot be styled through ordinary means. Until 57, it was possible but that's no longer going to work

There is going to be a [WebExtensions API triage](https://discourse.mozilla.org/t/october-17-webextensions-apis-triage/20386) tomorrow (Oct 17, 2017)... one of the subjects will be about [styling scrollbars](https://bugzilla.mozilla.org/show_bug.cgi?id=1402791). Join in if you feel strongly about it.

**Comment by silverwind** [comment] 2017-10-17 05:14
I won't be able to make it, but I left a summary in https://bugzilla.mozilla.org/show_bug.cgi?id=1402791#c5.

**Comment by xt0rted** [comment] 2017-12-01 02:00
With the final release of Win10 Fall Creators Update I'm no longer seeing these issues with the heart emoji in Chrome, Edge, or Firefox.

**Comment by silverwind** [comment] 2017-12-01 04:54
Okay, guess we can close this then.

**Closed by silverwind** 2017-12-01 04:54 UTC
