### ISSUE TITLE
Inverted color / whiteout on Insights Network page

### ISSUE THREAD

**Issue by itsmeow** [StylishThemes/GitHub-Dark#1108] opened 2020-05-03 05:10 UTC
* **Browser**:  Firefox Developer Edition
* **Operating System**: Windows 10 Pro
* **Link to page with the issue**: https://github.com/itsmeow/betteranimalsplus/network
* **Screenshot**: 
With:
![image](https://user-images.githubusercontent.com/10366817/80899150-a78cc080-8cda-11ea-8a30-95af271e34c5.png)
Without:
![image](https://user-images.githubusercontent.com/10366817/80899153-b5dadc80-8cda-11ea-8d2e-a30db2e42208.png)

**Comment by Mottie** [comment] 2020-05-03 13:19
Hi @itsmeow!

This is a duplicate of a long-standing issue of which we don't have a _good_ solution. See https://github.com/StylishThemes/GitHub-Dark/issues/961.

**Closed by Mottie** 2020-05-03 13:19 UTC
Labels: duplicate :camel:
