### ISSUE TITLE
background image enhancement

### ISSUE THREAD

**Issue by k1nghat** [StylishThemes/GitHub-Dark#687] opened 2018-07-10 21:22 UTC
add 'none' to the background image dropdown so it is just the flat gray.

**Comment by Mottie** [comment] 2018-07-10 23:06
Hi @k1nghat!

If you're referring to the custom settings on https://userstyles.org/styles/37035/github-dark, then set the "Add a background image?" dropdown to "No".

![](https://user-images.githubusercontent.com/136959/42542309-f85c7272-846b-11e8-88a9-8a3031752671.png)

**Comment by Mottie** [comment] 2018-07-10 23:11
If you're using GitHub Dark Script, then set the image to "none"

![](https://user-images.githubusercontent.com/136959/42542440-86a6a8e0-846c-11e8-8469-d5a0e74cd7ae.png)

Or, if you're using Stylus' usercss, then set that background image setting to "none"

![](https://user-images.githubusercontent.com/136959/42542480-a70fd5c0-846c-11e8-83ba-988394047438.png)

**Comment by k1nghat** [comment] 2018-07-10 23:15
ty for the reply. i was talking about stylus settings. figured an option as a drop down with the 'tiled' and 'fit window size' so you could easily go back to using the image that is entered by default.

**Comment by Mottie** [comment] 2018-07-10 23:17
The problem is that the variables in the usercss are limited. You can always use the "Reset" button to switch back to the defaults.

**Comment by k1nghat** [comment] 2018-07-10 23:19
i see. ty for your help!

**Comment by Mottie** [comment] 2018-07-10 23:30
Also, this is related to #656.

**Comment by the-j0k3r** [comment] 2018-07-11 08:46
> Also, this is related to #656.

:+1: adding none as option could be part of #656 final solution, two birds one stone. :100:

**Comment by Mottie** [comment] 2018-07-11 12:54
It would be possible if the current usercss variables could be nested. I mean we could switch to using the stylus preprocessor to do it, but I tried to keep the variables consistent so our usercss would work in both [Stylus](https://github.com/openstyles/stylus/wiki/Usercss#choose-a-preprocessor) (CSS, LESS, Stylus language, USO placeholders) and [xStyle](https://github.com/FirefoxBar/xStyle/wiki/Style-format#use-advanced-options-in-styles) (CSS, LESS & USO placeholders). Maybe I could figure out a way to use css variables to accomplish it...

**Comment by the-j0k3r** [comment] 2018-07-11 14:12
Yes, I found the need for something somewhat similar while doing some work on Stylus DeepDark, more precisely that you cant select 1 theme and all the colors/areas for that theme get applied, thus eliminating the mix and match of potentially weird combinations that may cause some things to not work as they were designed.

Sadly the only solution I could think of would make any style of that type huge.

I love userCSS but its rather limited in how you can use it for much needed advanced configuration types.

**Comment by the-j0k3r** [comment] 2019-05-04 16:04
@Mottie now that USO isnt a problem, what about a revisit of this?

**Comment by Mottie** [comment] 2019-05-04 19:21
Try v1.21.48.

**Comment by xt0rted** [comment] 2019-05-05 00:16
@Mottie it's working for me.

**Comment by the-j0k3r** [comment] 2019-05-05 07:31
closed by https://github.com/StylishThemes/GitHub-Dark/commit/6944c4f893cbd5b6179fe7205c0661512d23c469

2 issues closed here, thx.

**Closed by the-j0k3r** 2019-05-05 07:31 UTC
Labels: enhancement ⭐
