### ISSUE TITLE
Comment header bar in white - can't figure out why

### ISSUE THREAD

**Issue by smseidl** [StylishThemes/GitHub-Dark#1023] opened 2019-11-01 16:37 UTC
![NotDark](https://user-images.githubusercontent.com/23556348/68040015-64a24f80-fc9b-11e9-95bb-af73c3ef401d.png)

Please see attached screenshot with GitHub-Dark theme.  I can't get this header bar to get colored like the rest of the page.  I believe this is in the "comment-form-head tabnav" div class.

I have had to 'customize' GitHub-Dark to work with our on-prem GitHub enterprise (using the on-domain options) so I'm guessing it's related to that somehow.  This did work in an earlier version on my old laptop... not sure when I last updated that.  

Any help would be greatly appreciated.

**Comment by the-j0k3r** [comment] 2019-11-02 11:36
@smseidl Its hard to have a guess when we dont know what you changed and what version of GHD you used vs the GHE version in use.

First thing would be you posting your modified style in a gist and link back here, Ill have a look and see if I can spot anything obvious.
But mind I dont have Enterprise access so no idea there at all.

**Comment by xt0rted** [comment] 2019-11-02 15:55
This looks like a duplicate of #989

**Comment by the-j0k3r** [comment] 2019-11-03 06:28
It also looks like that to me. thanks.

Closing in favor of #989 with same requirements for information,

**Closed by the-j0k3r** 2019-11-03 06:28 UTC
Labels: help wanted :pray:
