### ISSUE TITLE
Branch name does not display properly

### ISSUE THREAD

**Issue by HerrHulaHoop** [StylishThemes/GitHub-Dark#903] opened 2019-04-01 14:28 UTC
Branch name in the outdated message escapes the dark theme. Here's a [link to the page](https://github.com/RPCS3/rpcs3/pull/5749) but the message will disappear if the PR is rebased on latest master.

Default theme:
![Screenshot (83)](https://user-images.githubusercontent.com/31934788/55334569-23548200-54b7-11e9-81fa-602b4e62a53d.png)

Dark theme:
![Screenshot (82)](https://user-images.githubusercontent.com/31934788/55334567-22bbeb80-54b7-11e9-920c-4538b97eb97c.png)

You can see the "master" doesn't change to match the theme. 

Here's the HTML surrounding it:
![Screenshot (85)](https://user-images.githubusercontent.com/31934788/55334822-a5dd4180-54b7-11e9-8cb7-806b08990d06.png)

Adding "span.branch-name" [here](https://github.com/StylishThemes/GitHub-Dark/blob/f1d5bb608561ae5c5a73151ee99b04d417739026/github-dark.css#L1215) seems to fix the issue but I don't know if that's the correct way to do it. Do let me know in case any further details are required.

**Comment by the-j0k3r** [comment] 2019-04-01 16:46
Hi there =), thank you for reaching out with this report.

Seems the issue is that the auto generated selector we have under /* auto-generated rule for "color: #0366d6" */ `a.branch-name` under `base-color`  is being broken by the prefixed `a`.

Should be fixed for next release one way or the other =), Ive an errand to run, but Ill get this in a few.

Thanks.

**Closed** 2019-04-01 16:53 UTC

**Comment by the-j0k3r** [comment] 2019-04-01 16:55
Turns out it was a different default color that the other autogenerated rule... Fixed though =) on next release.
