### ISSUE TITLE
Style improvement for mobile tabs

### ISSUE THREAD

**Issue by ClownMonster** [StylishThemes/GitHub-Dark#1021] opened 2019-10-31 11:37 UTC
**Describe the change you'd like**

**Additional context**
You can try to improve the look for the mobile tabs as it is not well fitted to it

**Comment by the-j0k3r** [comment] 2019-10-31 12:48
@ClownMonster thanks for opening this feature req, however this is a duplicate of https://github.com/StylishThemes/GitHub-Dark/issues/924

Thanks

**Closed by the-j0k3r** 2019-10-31 12:48 UTC
Labels: feature :heart_eyes:
