### ISSUE TITLE
mobile - Insights page / navigation -broken 

### ISSUE THREAD

**Issue by the-j0k3r** [StylishThemes/GitHub-Dark#1159] opened 2020-06-30 07:44 UTC
* **Browser**: Firefox 77.0.1 (64-bit)
* **Operating System**: Not applicable
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/pulse
* **Screenshot**:

Not only is this page broken, but the functionality of looking at all aspects of the project and contributions is GONE. in a way.

![Screenshot_2020-06-30 StylishThemes GitHub-Dark](https://user-images.githubusercontent.com/31389848/86097884-9cc19280-bab5-11ea-9a93-a90e8c7122a5.png)

The actual functionality thats gone is https://github.com/StylishThemes/GitHub-Dark/network/members

So essentially this is a huge upstream bug. navigation is broken when using a mobile user-agent  in this portion now. Clicking the insights link directs you to pulse and not insights as before.

Desktop style is fine.

@xt0rted, maybe your channels you can report this to someone that can fix the navigation link issues on mobile?

**Comment by xt0rted** [comment] 2020-06-30 07:50
That's the mobile view you're looking at. The desktop view still has everything.

**Comment by the-j0k3r** [comment] 2020-06-30 07:53
Im not using devtools Im using an useragent switcher, and doesnt work, only way to get to right page is clicking on forks which goes to https://github.com/StylishThemes/GitHub-Dark/network/members

**Comment by xt0rted** [comment] 2020-06-30 08:00
The styling should be fixed by 641fe9ccf38f3d0f11fca3197c2dec4b06abfe60, other than that I'm not sure what the issue is here. Mobile views were always missing things due to their smaller size and some pages you couldn't get to at all if they didn't have a mobile view.

**Comment by the-j0k3r** [comment] 2020-06-30 08:03
If you dont see an issue, then its broken by design.

**Comment by silverwind** [comment] 2020-06-30 18:01
Looks alright currently, I think this was fixed by https://github.com/StylishThemes/GitHub-Dark/commit/641fe9ccf38f3d0f11fca3197c2dec4b06abfe60.

Of note to Firefox users: Setting responsive design mode is apparrently not enough to trigger the mobile view presumably because GitHub's user agent sniffing is not detecting the mobile Firefox UA, only Chrome's.

**Closed by silverwind** 2020-06-30 18:01 UTC
Labels: bug :bug:

**Comment by the-j0k3r** [comment] 2020-06-30 21:15
I use a UA switcher with 

```
Mozilla/5.0 (Android 9; Mobile; rv:77.0) Gecko/77.0 Firefox/77.0
```

Seems to work

**Comment by xt0rted** [comment] 2020-06-30 21:46
In the responsive view there's a device picker just like in chrome, select one of those instead of the default `Responsive` and the correct UA string still be used for that device and the site will show the mobile view when you reload.

Don't ask why the menu isn't showing in the right spot, it seems FF doesn't handle resolution scaling correctly and puts it in the wrong spot.

![image](https://user-images.githubusercontent.com/831974/86180021-55f58c00-baf9-11ea-9025-f009d34475c8.png)

**Comment by silverwind** [comment] 2020-06-30 22:00
Ah, I was setting it to iPad which apparently gets the desktop view, but iPhone does get mobile.
