### ISSUE TITLE
Menu on SettingsPage not visible

### ISSUE THREAD

**Issue by 0xflotus** [StylishThemes/GitHub-Dark#1128] opened 2020-06-18 06:56 UTC
* **Browser**: Firefox 
* **Operating System**: MacOS
* **Link to page with the issue**: https://github.com/settings/profile
* **Screenshot**:

<img width="1457" alt="Bildschirmfoto 2020-06-18 um 08 55 12" src="https://user-images.githubusercontent.com/26602940/84988007-845e8900-b141-11ea-88e4-84296c9e4715.png">

**Comment by the-j0k3r** [comment] 2020-06-18 10:14
It is all visible here please [click here force update Github Dark.](https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css)

**Comment by s00172994** [comment] 2020-06-18 10:26
On version 2.0.113 (force update), using Chrome with cache disabled, still get this issue my end.

**Comment by s00172994** [comment] 2020-06-18 10:30
> It is all visible here please [click here force update Github Dark.](https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css)
> 
> This is proof it works with v2.0.113
> 
> ![Screenshot_2020-06-18-Build-software-better,-together](https://user-images.githubusercontent.com/31389848/85008632-82a2be80-b15d-11ea-8184-229b6ed9a643.png)

This issue is only showing on feature preview.

**Comment by the-j0k3r** [comment] 2020-06-18 10:41
Feature previews are beta the current devs need to be able to access the feature previews in order to fix it and also it seems like Github maybe using separate stylesheets now.

To understand the issues read owner/contributors replies at https://github.com/StylishThemes/GitHub-Dark/issues/1123

for now, dont enable feature previews while kinks are worked out.

cc @silverwind @xt0rted

**Comment by the-j0k3r** [comment] 2020-06-18 10:43
Also this is a duplicate of https://github.com/StylishThemes/GitHub-Dark/issues/1123

**Closed by the-j0k3r** 2020-06-18 10:43 UTC
Labels: bug :bug:
