### ISSUE TITLE
Active nav bar button for github.com/pulls is unreadable (blue text on blue bg)

### ISSUE THREAD

**Issue by ctrlrsf** [StylishThemes/GitHub-Dark#462] opened 2017-02-15 16:34 UTC
When you visit github.com/pulls and click on Created, Mentioned, or Assigned on the top nav bar, the button color changes to a blue background. The text is also blue so button text is unreadable. See screenshots for detail.

URL: github.com/pulls
Browser: Safari 10.0.3

<img width="500" alt="screenshot 2017-02-15 11 21 48" src="https://cloud.githubusercontent.com/assets/6004738/22984178/8e537c1c-f372-11e6-8727-aebbd74cbe0d.png">

<img width="300" alt="screenshot 2017-02-15 11 27 58" src="https://cloud.githubusercontent.com/assets/6004738/22984185/9447f044-f372-11e6-938e-0e0e9ea97ba0.png">

### Unstyled Content

- [x] I am using the most up-to-date GitHub Dark style!
- [x] No other existing issue and/or pull request.
- [x] Provide the URL of the unstyled content.

**Comment by Mottie** [comment] 2017-02-15 16:42
Hi @ctrlrsf!

I am not seeing the same issue... my base color is `#6D8048` in this screenshot

![](https://cloud.githubusercontent.com/assets/136959/22984572/67777668-f36b-11e6-8f5f-8ec238c27e1d.gif)

**Comment by ctrlrsf** [comment] 2017-02-15 17:35
@Mottie My base color is #4183C4 and my style is up to date. I also uninstalled and re-installed it just in case. Note, only see this issue with Safari. Is that a screengrab of Safari in your comment?

**Comment by Mottie** [comment] 2017-02-15 18:01
No, I use Chrome. I don't own any apple products. @silverwind, would you please check this out?

**Comment by silverwind** [comment] 2017-02-16 01:19
Can reproduce. There's a whole lot more link colors wrong in Safari because of a weird specificity issue. `a:not([href*="/labels/"])` is winning over `a.header-nav-link`, despite the latter coming later in the stylesheet.

I think Safari might be violating the CSS spec here, but we can see if something can be done about the `a` selector. Maybe we can finally remove the `labels` hack so this won't be an issue.

**Comment by xt0rted** [comment] 2017-02-16 02:01
Edge has the same problem with styles not applying the same as in Chrome. I had to setup a custom style sheet to fix these as they came up [xt0rted/edge-github-dark#edge.css](https://github.com/xt0rted/edge-github-dark/blob/master/edge.css)

**Comment by ctrlrsf** [comment] 2017-02-16 16:19
I'm seeing some other style issues with Safari compared to Chrome that might be related.

Notice the commit messages (which are links) are blue (base color) in Safari. Chrome they're grey. These blue links on top of the blue background in the /pulls tab is why I can't see them.

Both Safari and Chrome have updated themes as of 11AM.

I tested with Safari Technology Preview and it looks the same as Safari (10.0.3).

Safari:
![image](https://cloud.githubusercontent.com/assets/6004738/23029568/ffa0ca5c-f438-11e6-9048-2930a1710a60.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/6004738/23029640/3ab445ce-f439-11e6-9b70-ba3bef240d8c.png)

**Comment by silverwind** [comment] 2017-02-16 19:37
I've found two issues for Safari:

- https://github.com/350d/stylish/issues/25
- GitHub seems to serve different HTML to Safari than to Chrome/Firefox. The header has the class `.site-header` on Chrome/Firefox but just `.header` on Safari. Just great. 😩

I can't really test Edge unless I boot a VM, so focus will be on Safari first.

**Comment by silverwind** [comment] 2017-02-16 20:22
@ctrlrsf update Stylish to 1.9.8 and possibly reinstall the style.

**Comment by silverwind** [comment] 2017-02-16 20:34
Oh, and uncheck the minify option in Stylish too.

**Comment by silverwind** [comment] 2017-02-16 20:39
@xt0rted which extension are you using in Edge?

**Comment by xt0rted** [comment] 2017-02-16 20:44
@silverwind I setup my own because Tampermonkey doesn't work due to security header issues, and Stylish/Stylus isn't available yet. [xt0rted/edge-github-dark](https://github.com/xt0rted/edge-github-dark) can be side loaded in Chrome or Edge to apply the GitHub-Dark theme.

**Comment by xt0rted** [comment] 2017-02-16 21:29
@silverwind it's been awhile since I reviewed the Edge specific styles. I've turned them off so I can see what ones are still needed. A fair amount has been fixed by the looks of it but there's still some basic ones that are needed. If you go to take a look at this let me know so I can make sure you have the most current version.

**Comment by ctrlrsf** [comment] 2017-02-17 13:29
@silverwind That did it! Looks perfect now. Had to install Stylish 1.9.8 manually from http://sobolev.us/stylish/ because version on Apple's extension website is 1.9.1.

**Closed** 2017-02-17 18:09 UTC

**Comment by silverwind** [comment] 2017-02-18 07:38
@xt0rted we could make a small Edge-specific section in the style if you like. I'd appreciate a pull request.
