### ISSUE TITLE
Comments are dark, on a dark background

### ISSUE THREAD

**Issue by patosai** [StylishThemes/GitHub-Dark#994] opened 2019-09-06 18:15 UTC
* **Browser**: Firefox 69
* **Operating System**: OS X 10.14
* **Link to page with the issue**: N/A
* **Screenshot**:  
![螢幕快照 2019-09-06 上午11 04 57](https://user-images.githubusercontent.com/5304405/64450100-3edf3c80-d096-11e9-936a-f5e7f63295f3.png)
![螢幕快照 2019-09-06 上午11 20 01](https://user-images.githubusercontent.com/5304405/64451073-499ad100-d098-11e9-8d71-33b73714eecb.png)

It looks like comments in multiple places (pull requests, review comments, etc) have a dark color on a dark background.

I fixed it for now by adding `.comment-body {color: #CCC}` to the Stylus sheet.

**Comment by patosai** [comment] 2019-09-06 18:19
Right after opening this issue, I realized that the comments for pull requests also have the same issue.

**Comment by aaomidi** [comment] 2019-09-06 18:21
Duplicate of #993

**Closed** 2019-09-06 18:21 UTC
Labels: bug :bug:
