### ISSUE TITLE
Repo header remains white

### ISSUE THREAD

**Issue by pdonias** [StylishThemes/GitHub-Dark#1059] opened 2020-02-10 08:40 UTC
* **Browser**: Firefox 72.0.2 (64-bit)
* **Operating System**: Ubuntu 18.04.4 LTS
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/issues
* **Screenshot**:
![Capture_2020-02-10_09:32:12](https://user-images.githubusercontent.com/10992860/74133577-25b05e00-4be9-11ea-8c1d-423cad0930de.png)

**Comment by the-j0k3r** [comment] 2020-02-10 09:03
duplicate of https://github.com/StylishThemes/GitHub-Dark/issues/1057 and already fixed.

Please [click here](https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css) to ensure you upgrade to the latest version.

Thanks

**Closed by the-j0k3r** 2020-02-10 09:03 UTC
Labels: bug :bug:

**Comment by pdonias** [comment] 2020-02-10 09:05
Thanks @the-j0k3r!
